name: Kakao Notify

on:
  schedule:
    # 매일 오전 9시 KST == 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  # ✅ Saramin 크롤러 완료 직후 자동 실행
  workflow_run:
    workflows: ["Run Saramin Crawler"]   # ✅ 정확한 워크플로 이름
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Send Kakao message
        env:
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
          KAKAO_ACCESS_TOKEN: ${{ secrets.KAKAO_ACCESS_TOKEN }}
          PAGES_URL: "https://pkpjs.github.io/test/saramin_results_latest.html"
        run: |
          python send_kakao.py
